defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: chimpance99
  socket: /tmp/mysql.sock

development:
  database: laposta_development
  <<: *defaults

test: &test
  database: laposta_test
  <<: *defaults

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host:
  database: laposta_production
  pool: 5
  username:
  password:

cucumber:
  <<: *test